---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
spec:
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                -   name: postgres-db
                    image: postgres:13.4-alpine3.14
                    ports:
                        -   containerPort: 5432
                    envFrom:
                        -   secretRef:
                                name: postgres-credentials
                        -   configMapRef:
                                name: postgres-config
                    volumeMounts:
                        -   mountPath: /var/lib/pgsql/data
                            name: postgres-database-storage

                    livenessProbe:
                        exec:
                            command:
                                - /bin/sh
                                - -c
                                - exec pg_isready -U "soad" -d systemofadownload -h 127.0.0.1 -p 5432
                        failureThreshold: 6
                        initialDelaySeconds: 30
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 5
                    readinessProbe:
                        exec:
                            command:
                                - /bin/sh
                                - -c
                                - -e
                                - |
                                    exec pg_isready -U "soad" -d systemofadownload -h 127.0.0.1 -p 5432
                                    [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
                        failureThreshold: 6
                        initialDelaySeconds: 5
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 5
            volumes:
                -   name: postgres-database-storage
                    persistentVolumeClaim:
                        claimName: postgres-data-claim
