---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-data-volume
    labels:
        type: local
        app: postgres
spec:
    storageClassName: standard
    capacity:
        storage: 10Gi
    persistentVolumeReclaimPolicy: Retain
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/data"
