version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: system_of_a_download_zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka:2.12-2.1.1
        container_name: system_of_a_download_kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.1.241
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "artifact-changelog-analysis:1:1"
        volumes:
            - ./target/kafka:/kafka
    cassandra:
        image: library/cassandra:3.11
        container_name: system_of_a_download_cassandra
        ports:
            - "9042:9042"
        volumes:
            - ./target/cassandra/data:/var/lib/cassandra
            - ./target/cassandra/logs:/var/log/cassandra
    sonatype:
        image: sonatype/nexus3
        container_name: system_of_a_download_nexus
        ports:
            - "8081:8081"
        volumes:
            - nexus-data:/nexus-data

volumes:
    nexus-data:
